#pragma once
#include "sacred/address.h"

#include <cstdint>

namespace GameServer
{
    struct cApp;
}

// Addresses in gameserver.exe. They are found at startup from byte signatures (gameserver_sigs.inc, generated by
// tools/gen_sigs.py; the English and the German gameserver have the same code and addresses). The names match the
// Ghidra program "/GameServer.exe (GOG)". sacred.exe starts it for the games it hosts.
namespace GameServer::Addr
{
    // The application object and its network object (sacred/net.h).
    inline Sacred::Global<cApp*> g_pApp{};              // ENG 00634238

    // cNetServer_watchdogThread (0x4DBCB0) drops a connected player that has not sent its first message within
    // 5000 ms of connecting: `add edx, 5000` (imm32 here) on the connect time, compared with the current time.
    inline uintptr_t firstContactTimeoutImm{};          // ENG 004DC523
}
