#pragma once
#include <cstdint>

// Addresses in gameserver.exe. They are found at startup from byte signatures (gameserver_sigs.inc, generated by
// tools/gen_sigs.py; the German and the English gameserver have the same code). The comments give the German
// addresses, the names match the Ghidra program "/gameserver.exe (DE)". sacred.exe starts it for the games it hosts.
namespace GameServer::Addr
{
    // Application object; +0x40 the network object (cNetServer_ctor 0x4E8170).
    inline uintptr_t g_pApp{};                          // DE 00634238
    constexpr uintptr_t app_net = 0x40;

    // Network object. cNetServer_initNetwork (0x4E8AB0) creates the ping socket: UDP, SO_BROADCAST, connected to
    // 255.255.255.255:<ping port>. cNetServer_sendAnnouncement (0x4E99A0) fills the plain announcement, compresses
    // it and sends it with the only send() call in the exe; the version field is cleared again right after.
    constexpr uintptr_t net_pingSocket = 0x1A8;
    constexpr uintptr_t net_announcement = 0x596C;

    // cNetServer_watchdogThread (0x4DBCB0) drops a connected player that has not sent its first message within
    // 5000 ms of connecting: `add edx, 5000` (imm32 here) on the connect time, compared with the current time.
    inline uintptr_t firstContactTimeoutImm{};          // DE 004DC523
}
