#pragma once
#include <cstdint>

// Addresses in sacred.exe. They are found at startup from byte signatures (sacred_sigs.inc, generated by
// tools/gen_sigs.py from the English GOG build and checked against the German one); the comments give the English
// addresses, the names match the Ghidra program "/Sacred.exe (GOG)".
namespace Sacred::Addr
{
    // dxDriver7 (DirectDraw7 + Direct3D7 wrapper, one global instance)
    inline uintptr_t dxDriver7_init{};                  // ENG 00645260
    inline uintptr_t dxDriver7_flip{};                  // ENG 00645E40
    inline uintptr_t dxDriver7_lockBack{};              // ENG 00646150
    inline uintptr_t dxDriver7_drawLoadingScreen{};     // ENG 006468A0

    // cDxDevices::findMode(w, h, bpp, flags) -> mode record; called once by initApp with 1024x768.
    inline uintptr_t cDxDevices_findMode{};             // ENG 00644130

    // Return address of the CreateWindowExA call that creates the main game window.
    inline uintptr_t mainWindowCreateReturn{};          // ENG 00813C87

    // The main window procedure (sacredWndProc, ENG 00812BF0) pauses all rendering on WM_ACTIVATEAPP: bit 0x20000 of
    // the engine flags (ENG 0182EE38), which the menu and game render loops and the intro movies also test. These
    // are its windowed-mode clear and set of the bit (the game's fullscreen mode handles it separately).
    inline uintptr_t activateAppResumeAnd{};            // ENG 00812D95; and eax, 0xFFFDFFFF (activated)
    inline uintptr_t activateAppPauseOr{};              // ENG 00812DC8; or eax, edi (edi = 0x20000; deactivated)

    // Mouse: getClientCursorPos(hwnd, POINT*) is the only cursor read; cMouse is the singleton the UI and world poll.
    inline uintptr_t getClientCursorPos{};              // ENG 0066E280
    inline uintptr_t cMouse_instance{};                 // ENG 00654F60
    inline uintptr_t cMouse_renderCursor{};             // ENG 00655450; (device, flag)

    // Renders the hero into the back buffer and reads the centered region back for the savegame JPEG.
    inline uintptr_t renderSavePortrait{};              // ENG 004B1450; thiscall (path, w, h, scale), this = 0xAACF80
    // Plays an intro/cutscene video through DirectShow onto a fullscreen 1024x768 TL quad. thiscall on the movie
    // player (+4 skip count, +8 HWND): (IDirectDraw*, primary IDirectDrawSurface*, IAMMultiMediaStream*, 640, 480);
    // returns -1 when skipped.
    inline uintptr_t playVideo{};                       // ENG 006A0EA0
    // cdecl (const char* path, IDirectDraw*, IAMMultiMediaStream** out) -> HRESULT: amstream with the DirectDraw
    // video stream, the default audio renderer and the file opened. The caller plays it if *out is set.
    inline uintptr_t openMovieStream{};                 // ENG 006A0D80

    // UI framework (cUI_Control2 / cUI_Window2 / cUI_Manager)
    inline uintptr_t g_pUiManager{};                    // ENG 017EEBBC; cUI_Manager*
    inline uintptr_t cUI_Manager_isCursorOverUi{};      // ENG 0075AA90; thiscall (x, y) -> bool, UI coordinates
    // Creates the in-game windows (UiManager::taskbar ...) once; later calls return right away.
    inline uintptr_t cUI_Manager_createGameWindows{};   // ENG 00759AF0; fastcall (manager)
    // The help screen (H key, UiManager::helpScreen): cUI_Manager_render calls it every frame with the screen for
    // the open windows (1 none, 2 inventory, 3 blacksmith, 4 combo master, 5 merchant, 6 world map, 7 rune exchange).
    // It puts the manager's help popups (UiManager::helpPopups) at fixed 1024x768 positions, each next to or over
    // the window it explains, and sets their texts. Without the help screen it shows the [H] and [TAB] hints instead.
    inline uintptr_t cUI_Manager_showHelp{};            // ENG 0075B4F0; thiscall (device, short screen)
    // Popup (tooltip / hint) windows, owned by the manager (UiManager::popupsBegin). Callers set the popup's x/y
    // first, then its text with one of these, which also requests a new layout: the popup's render (vtable +0x14)
    // centers it on x/y and clamps it into 16..1008 x 16..752 before drawing.
    inline uintptr_t cUI_Popup_setText{};               // ENG 006E6EA0; thiscall (?, const wstring*, bool)
    inline uintptr_t cUI_Popup_setTextId{};             // ENG 006E6FB0; thiscall (?, text id, bool)
    // The layout: sizes the popup to its text; unless flags (+0x154) have 2 it centers the popup on x/y; with 8 it
    // clamps it into 16..1008 x 16..752 (a popup that would leave the 1024x768 screen sticks to its edge); with 0x20
    // it centers it on the screen (512, 384); then clears 0x40 and, unless 0x200, lays out the children.
    inline uintptr_t cUI_Popup_layout{};                // ENG 006E7AF0; fastcall (popup)
    inline uintptr_t cUI_Window2_layoutChildren{};      // ENG 00727B30; fastcall (window)
    // Draws the item held by the cursor at the cursor; every window that takes items (inventory, chest, cube,
    // trade, merchant, blacksmith) calls it from its render with (device, 1).
    inline uintptr_t cInventoryEntry_render{};          // ENG 005DC430; thiscall (device, short)

    // UI-side reads of the cursor: cMouse_instance() followed by reads of +4/+8 only, and the calls of cMouse::getX
    // (ENG 00655850), getY (00655860) and getCursorPos. SacredBild gives them the cursor in the current UI frame.
    inline uintptr_t uiMouseReads[55]{};                // ENG 005DC316 006A3404 ... 00758A9D (tools/gen_sigs.py)
    inline uintptr_t uiGetXCalls[6]{};                  // ENG 005DC46B 006B6819 006B6FC7 006DADF5 006DBF81 006DD9E3
    inline uintptr_t uiGetYCalls[6]{};                  // ENG 005DC47B 006B6828 006B6FD6 006DAE04 006DBF90 006DD9F2
    inline uintptr_t uiCursorPosCalls[5]{};             // ENG 005DC495 006AD204 006C01A2 006EA500 006EA589
    // thiscall (int* x, int* y): the drawn cursor's top-left corner (+0xC/+0x10 minus the cursor's hot spot); writes
    // nothing while no cursor image is set (+0x64).
    inline uintptr_t cMouse_getCursorPos{};             // ENG 00655810

    // Texture manager (one instance): loads textures on use, evicts least recently used ones above a budget.
    // initApp computes the budget from GlobalMemoryStatus and the reported video memory (min 32 MB).
    inline uintptr_t g_pTextureManager{};               // ENG 013E7838
    inline uintptr_t cTextureManager_init{};            // ENG 0065E7A0; thiscall (budgetBytes)

    // cEngine
    inline uintptr_t cEngine_renderThreadRun{};         // ENG 0060E350; fastcall (engine), loops until shutdown
    // Frame limiter: cdecl (double, uint16 fps); spins with Sleep(0) until 1/fps passed since its last return.
    // The render loop calls it with 60 before each flip (skipped if 0x182EE3C has 0x4000), the menu loop too.
    inline uintptr_t frameLimiter{};                    // ENG 0060A9F0
    inline uintptr_t renderLimiterReturn{};             // ENG 0060EA6E
    // cEngine_updateWorldCursor (0x611E70) asks the UI whether the cursor is over a window before picking.
    inline uintptr_t worldCursorUiTestCall{};           // ENG 00611EE3
    inline uintptr_t captureLockBackReturn{};           // ENG 006136AB; after captureInternal's call to lockBack
    // Screenshots: dxDriver7_startCapture (ENG 00648660, thiscall (frames)) sets dxDriver7 +0xA8 (frames left) and
    // +0xAC (frames taken); every caller (Print Screen, the game's screenshot key, a debug key) asks for one frame.
    // While +0xA8 is set, dxDriver7_flip locks the back buffer and calls captureScreenshot: mode -1 = one screenshot,
    // written by writeTga1024x768 (ENG 006482C0) as .\Capture\shotNNNN.tga, which a thread (ENG 00648430) converts to a
    // quality 50 JPEG through IJL. Both assume 1024x768 (the 32-bit path ignores the pitch). Modes >= 0 copy 3 MB
    // frames into a mapped file ("vidobj"), < -1 write them out as cap%04d.tga: only reached with more than one frame.
    inline uintptr_t captureScreenshot{};               // ENG 006487D0; cdecl (bits, pitch, mode)

    // World <-> pixel conversion (cdecl (out, point, rotation, projection) -> out). Pixels assume a projection
    // spanning 1024x768 pixels: true for g_unzoomedProjection, not for the device projection (W x H).
    inline uintptr_t pixelsToWorld{};                   // ENG 00623940
    inline uintptr_t worldToPixels{};                   // ENG 00623B60
    inline uintptr_t g_unzoomedProjection{};            // ENG 0182ED70

    // Ground: renderTileRow draws each tile's base through the quad batcher (cWorldView + 0x86890) and collects
    // tiles with blend layers into a fixed array (at most 0x6D5 per frame); after all rows cWorldView0_render
    // flushes the batcher and cWorldView_drawTileLayers draws the collected layers.
    inline uintptr_t cWorldView_renderTileRow{};        // ENG 0062AE90; thiscall (device, rowPos, detail)
    inline uintptr_t cWorldView_drawTileLayers{};       // ENG 0062D3C0; thiscall (device)
    inline uintptr_t cQuadBatcher_flush{};              // ENG 00629340; thiscall (device)
    // Draws the collected water/lava tiles (glow pass, then the tiles) and sets the water ambience from their
    // count and average position.
    inline uintptr_t cWorldView_drawWaterTiles{};       // ENG 0062DD00; thiscall (device)
    // Row walk: initRowWalk sets the even and odd row positions (WorldView::rowEven/rowOdd) from the view's top-left
    // corner; cWorldView0_render then calls renderTileRow for each and steps it one tile row down (tile + 0x41,
    // y + 48), changing sector at sector edges. The camera position (view coordinates) is set by the same frame.
    inline uintptr_t cWorldView_initRowWalk{};          // ENG 006328C0; thiscall (pos: +4 x, +8 y; map data)
    inline uintptr_t g_viewCameraX{};                   // ENG 00AD7998; int32
    inline uintptr_t g_viewCameraY{};                   // ENG 00AD799C; int32

    // Engine input: cEngine_receiveEvent (0x618090) passes mouse events to the UI manager first (UI coordinates)
    // and then to the world mouse handler, which picks with the event position.
    inline uintptr_t cEngine_worldMouse{};              // ENG 006172C0; thiscall (event, flag) -> bool
    inline uintptr_t cEventMouseDown_vtable{};          // ENG 0089704C; x at +8, y at +0xC
    inline uintptr_t cEventMouseUp_vtable{};            // ENG 00899248
    // World-side cursor reads, redirected to physical coordinates: calls to cMouse::getX (ENG 00655850),
    // cMouse::getY (00655860) and cMouse_instance.
    inline uintptr_t worldGetXCalls[6]{};               // ENG 00611F54 00611F9D 0061273C 006127C8 00617DFC 00617E69
    inline uintptr_t worldGetYCalls[6]{};               // ENG 00611F47 00611F90 0061274D 006127D9 00617E0D 00617E5C
    inline uintptr_t worldMouseReads[5]{};              // ENG 004FB881 0060F268 006104C7 00611EC3 0062764E

    // Record caches of the map data object (constructor 0x6335F0, clear 0x633E80): thiscall (id) -> record, 0 if
    // id is 0. Each looks the id up in its own std::map<uint32_t, record> (find 0x640410: thiscall (&key) on the
    // map, returns the node or the head as end; node +0x10 key, +0x14 record), stamps the node with the current
    // time (0xCD7A50) on a hit, and on a miss reads the record from a data file, inserts it and may evict the node
    // with the oldest stamp. 0x635FE0 holds the ground layer records (16 bytes, map at +0xDE5C, stamp node +0x24),
    // 0x635E50 the 64-byte records also used by game logic (map at +0xDE50, stamp node +0x54).
    inline uintptr_t layerRecordCache{};                // ENG 00635FE0
    inline uintptr_t recordCache{};                     // ENG 00635E50
    inline uintptr_t recordMapFind{};                   // ENG 00640410
    inline uintptr_t g_recordStamp{};                   // ENG 00CD7A50

    // Game client (cGCclass, one instance). cGCclass_initNetwork (0x7D2BD0) binds a UDP socket (SO_REUSEADDR) to
    // NETWORK_PORT_LISTEN for the LAN list; cGCclass_pollLanGames (0x7D35F0) reads the gameservers' announcements
    // from it with select/__WSAFDIsSet/recvfrom (their only use in the exe) and drops games that were silent for
    // 5 s. cGCclass_joinLanGame (0x7D3D00) connects to the address inside the announcement.
    inline uintptr_t g_pGameClient{};                   // ENG 0182EBF0
    constexpr uintptr_t gameClient_lanSocket = 0x14;
    // cGCclass_initNetwork sets TinCat's drv_disable_nagle (TCP_NODELAY on the game connection) to
    // "data flow == LAN" (cGCclass + 0x40414 == 2): `cmp ebx, 2; sete al` after `xor eax, eax`.
    inline uintptr_t initNetworkNagleTest{};            // ENG 007D310E

    // cWorldView0 vtable slot 5: draws the isometric world (arg: device).
    inline uintptr_t cWorldView0_render{};              // ENG 00632140

    // cUI_Manager::render(device): letterbox bars + all UI windows.
    inline uintptr_t cUI_Manager_render{};              // ENG 00758ED0

    // Language. WinMain (0x817B30) sets g_language from settings.cfg's LANGUAGE (exact match with a code, else it
    // stays DE) or a code in lower case on the command line, formats ".\SCRIPTS\<code>\global.res" and passes it to
    // cTextTable_load, which ignores it in these builds: it loads the text from the exe's BINARY resource 107 (each
    // uint16 XORed with the one before it, the first with 0x45AD) into a buffer from the game's operator new.
    inline uintptr_t g_language{};                      // ENG 017E7D34; int32, index into g_languageCodes
    inline uintptr_t g_languageCodes{};                 // ENG 00899394; char[16] each: US DE FR SP IT PL HU JP VC RU CZ
    constexpr int languageCount = 11;
    inline uintptr_t cTextTable_load{};                 // ENG 0080E680; thiscall (path) -> bool, this = g_textTable
    inline uintptr_t textTableAllocCall{};              // ENG 0080E6F0; its `call operator new` (cdecl (size))
    // Speech and sound effects: cMSS's constructor (only called by the instance getter 0x6770E0, on first use) opens
    // g_soundPakPath once and keeps the FILE*. initApp copies ".\PAK\SOUND.PAK" there (cMSS_setPakPath 0x677160)
    // and creates cMSS, but the startup movies (0x6A16E0, called from initApp before that) can create it first,
    // with the buffer's initial ".\PAK\SOUND.PAK".
    inline uintptr_t cMSS_ctor{};                       // ENG 00676200; thiscall (44100, 16, 1)
    inline uintptr_t g_soundPakPath{};                  // ENG 009D760C; char[256]
}

// Text table (g_textTable, ENG 0182ED50; a static object, destroyed at exit). global.res, in memory as on disk:
// uint32 count, count entries {uint32 id, uint32 offset, uint32 flags, uint32 bytes} by ascending id, then the
// UTF-16 strings; an entry's string starts at 4 + offset.
namespace Sacred::TextTable
{
    constexpr uintptr_t data = 0x00;         // uint8_t*
    constexpr uintptr_t size = 0x04;         // uint32 bytes
}

// dxDriver7 member offsets (identical in the English and German builds).
namespace Sacred::DxDriver
{
    constexpr uintptr_t height = 0x1C;       // uint16
    constexpr uintptr_t width = 0x20;        // uint16
    constexpr uintptr_t windowed = 0x90;     // 1 = fullscreen, else windowed
    constexpr uintptr_t bpp = 0x94;
    constexpr uintptr_t ddraw = 0xB4;        // IDirectDraw7*
    constexpr uintptr_t back = 0xBC;         // IDirectDrawSurface7* (3D render target)
    constexpr uintptr_t device = 0xCC;       // IDirect3DDevice7*
}

// cUI_Control2 member offsets.
namespace Sacred::UiControl
{
    constexpr uintptr_t flags = 0x10;        // bit 0: visible
    constexpr uintptr_t x = 0x24;
    constexpr uintptr_t y = 0x28;
    constexpr uintptr_t width = 0x2C;        // int16
    constexpr uintptr_t height = 0x2E;       // int16
}

// cEngine member offsets.
namespace Sacred::Engine
{
    constexpr uintptr_t flags = 0x54;        // 0x10000 loading screen, 0x20000 fade out, 0x40000 fade in, 0x80000 black
}

// cWorldView member offsets (ground layers).
namespace Sacred::WorldView
{
    constexpr uintptr_t quadBatcher = 0x86890;
    constexpr uintptr_t layeredTileCount = 0x3FF1C;
    constexpr uint32_t layeredTileCapacity = 0x6D5;
    // Animated (water/lava, record type 0x90/0xA0) tiles: renderTileRow appends 0x98-byte entries at +0x3FF2C without
    // a bounds check; cWorldView_drawWaterTiles draws them after all rows. Entry 1750 would overwrite the count.
    constexpr uintptr_t waterTileCount = 0x80E3C;
    constexpr uint32_t waterTileCapacity = (0x80E3C - 0x3FF2C) / 0x98;
    // Row walk positions: x, y (float), tile (int16, row * 64 + column in its sector), sector (int16, 3x3 grid of
    // loaded sectors around the camera, row * 3 + column), steps (int16).
    constexpr uintptr_t rowEven = 0x970D4;
    constexpr uintptr_t rowOdd = 0x970E4;   // even + (48, 24): one tile column further
    constexpr uintptr_t rowEdgeLeft = 0x96AB8;  // 6: renderTileRow draws ground from column edgeLeft - 1 ...
    constexpr uintptr_t rowEdgeRight = 0x96ABC; // 6: ... to column rowLength - edgeRight + 1 (rest: margins)
    constexpr uintptr_t rowLength = 0x96AC8;    // tiles per row: view width / 96 + 12
}

// cTextureManager member offsets.
namespace Sacred::TextureManager
{
    constexpr uintptr_t usedBytes = 0xC001C;
    constexpr uintptr_t budgetBytes = 0xC0020;
}

// cMouse member offsets.
namespace Sacred::Mouse
{
    constexpr uintptr_t x = 0x04;
    constexpr uintptr_t y = 0x08;
    constexpr uintptr_t cursorImage = 0x64;  // getCursorPos writes its outputs only while this is set
}

// cUI_Manager member offsets. The in-game windows created by createGameWindows are pointers in
// firstGameWindow..lastGameWindow.
namespace Sacred::UiManager
{
    constexpr uintptr_t flags = 0x08;        // 0x01 menus, 0x04 in game, 0x10 cinematic
    constexpr uint32_t inGame = 0x04;
    constexpr uint32_t helpScreen = 0x200;   // the help screen (H key) is shown
    // uint16[16]: indices into the popups (popupsBegin) used by the help screen, in the order of its entries.
    constexpr uintptr_t helpPopups = 0x56;
    constexpr uintptr_t firstGameWindow = 0x80;
    constexpr uintptr_t lastGameWindow = 0xD8;
    // In-game windows (cUI_Window2 subclasses) that SacredBild places, with their rects in the 1024x768 layout.
    constexpr uintptr_t taskbar = 0x80;      // 0,676 1024x92
    constexpr uintptr_t inventory = 0x84;    // 0,388 640x256
    constexpr uintptr_t equipment = 0x88;    // 656,388 256x256
    constexpr uintptr_t blacksmith = 0x8C;   // 0,0 640x352
    constexpr uintptr_t merchant = 0x90;     // 0,0 640x336
    constexpr uintptr_t minimap = 0x9C;      // UI_WND_MERC: minimap and party portraits, 932,0 92x676
    constexpr uintptr_t stats = 0xA0;        // 656,0 256x420
    constexpr uintptr_t console = 0xA4;      // chat input, 256,640 512x128
    constexpr uintptr_t master = 0xB8;       // combat art master, 0,0 640x336
    constexpr uintptr_t chest = 0xC0;        // 0,0 640x320
    constexpr uintptr_t netPortraits = 0xCC; // 0,0 896x64
    constexpr uintptr_t cube = 0xD4;         // 0,0 640x320
    constexpr uintptr_t trade = 0xD8;        // 0,0 640x320
    // std::vector of popup windows (vtable: render +0x14, events +0x10, hit test +0x1c, like a window).
    constexpr uintptr_t popupsBegin = 0x124;
    constexpr uintptr_t popupsEnd = 0x128;
}

// cUI_Window2 virtual functions (thiscall; byte offsets into the vtable) that SacredBild wraps for UI frames.
namespace Sacred::UiWindowSlot
{
    constexpr uintptr_t receiveEvent = 0x10; // (cEvent*) -> bool; mouse buttons carry x/y at +8/+0xC
    constexpr uintptr_t render = 0x14;       // (device)
    constexpr uintptr_t isInside = 0x1C;     // (x, y) -> bool
    constexpr uintptr_t show = 0x24;         // (bool)
    constexpr uintptr_t render2 = 0x44;      // (device, ?, ?): blacksmith, merchant, net portraits draw here
}

// cUI_Taskbar2 members.
namespace Sacred::Taskbar
{
    // Embedded button ("+", opens the character stats; blinks with flag 0x400000 while points are unspent). Placed at
    // the absolute position (898, 10) of the stats window's close button, which covers it while the window is open.
    constexpr uintptr_t levelUpButton = 0x18C;
    constexpr int levelUpX = 898;
    constexpr int levelUpY = 10;
}

// Popup (tooltip) window: a cUI_Window2 with its own flags.
namespace Sacred::Popup
{
    constexpr uintptr_t flags = 0x154;
    constexpr uint32_t clampToScreen = 0x08;    // layout keeps it 16 px inside the 1024x768 screen
    constexpr uint32_t centerOnScreen = 0x20;   // layout centers it on (512, 384)
    constexpr uint32_t keepChildren = 0x200;    // layout leaves the children where they are
}

// cEvent member offsets (mouse button events: cEventMouseDown_vtable / cEventMouseUp_vtable).
namespace Sacred::MouseEvent
{
    constexpr uintptr_t x = 0x08;
    constexpr uintptr_t y = 0x0C;
}
