#pragma once
#include "sacred/address.h"

#include <windows.h>
#include <unknwn.h>
#include <cstddef>
#include <cstdint>

struct IDirect3DDevice7;
struct IDirectDraw;
struct IDirectDrawSurface;

namespace Sacred
{
    struct cCreature;
    struct cEngine;
    struct cEvent;
    struct cGCclass;
    struct cMapData;
    struct cMouse;
    struct cMutex;
    struct cObject;
    struct cObjectManager;
    struct cOrder;
    struct cQuadBatcher;
    struct cSpriteBatcher;
    struct cTextResources;
    struct cTextTable;
    struct cTexture;
    struct cTextureManager;
    struct cUI_Book;
    struct cUI_Control2;
    struct cUI_Manager;
    struct cUI_NetworkInfo;
    struct cNetPlayers;
    struct cUI_Popup;
    struct cUI_Savegame;
    struct cUI_Slider;
    struct cUI_Window2;
    struct cFontManager;
    struct cWorldView;
    struct dxDriver7;
    struct LayerRecord;
    struct RecordMap;
    struct RenderFlags;
    struct RowPos;
    struct UiRect;
    struct WorldState;
}

// Addresses in sacred.exe. They are found at startup from byte signatures (sacred_sigs.inc, generated by
// tools/gen_sigs.py from the English GOG build and checked against the German one); the comments give the English
// addresses, the names match the Ghidra program "/Sacred.exe (GOG)".
namespace Sacred::Addr
{
    // dxDriver7 (DirectDraw7 + Direct3D7 wrapper, one global instance)
    // ENG 00645260
    inline Thiscall<uint32_t(dxDriver7* self, void* devices, void* deviceDesc, void* mode)> dxDriver7_init{};
    inline Thiscall<int(dxDriver7* self)> dxDriver7_flip{};  // ENG 00645E40
    inline Thiscall<void*(dxDriver7* self, void* desc)> dxDriver7_lockBack{}; // ENG 00646150
    // ENG 006468A0
    inline Thiscall<void(dxDriver7* self, uint32_t progress, const char* text)> dxDriver7_drawLoadingScreen{};

    // cDxDevices::findMode(w, h, bpp, flags) -> mode record; called once by initApp with 1024x768.
    inline Thiscall<void*(void* self, int w, int h, int bpp, int flags)> cDxDevices_findMode{}; // ENG 00644130

    // Return address of the CreateWindowExA call that creates the main game window.
    inline uintptr_t mainWindowCreateReturn{};          // ENG 00813C87

    // The main window procedure (sacredWndProc, ENG 00812BF0) pauses all rendering on WM_ACTIVATEAPP: bit 0x20000 of
    // the engine flags (ENG 0182EE38), which the menu and game render loops and the intro movies also test. These
    // are its windowed-mode clear and set of the bit (the game's fullscreen mode handles it separately).
    inline uintptr_t activateAppResumeAnd{};            // ENG 00812D95; and eax, 0xFFFDFFFF (activated)
    inline uintptr_t activateAppPauseOr{};              // ENG 00812DC8; or eax, edi (edi = 0x20000; deactivated)

    // Mouse: getClientCursorPos(hwnd, POINT*) is the only cursor read; cMouse is the singleton the UI and world poll.
    inline Cdecl<void(HWND window, POINT* pt)> getClientCursorPos{}; // ENG 0066E280
    inline Cdecl<cMouse*()> cMouse_instance{};          // ENG 00654F60
    inline Thiscall<void(cMouse* self, IDirect3DDevice7* device, int flag)> cMouse_renderCursor{}; // ENG 00655450

    // Renders the hero into the back buffer and reads the centered region back for the savegame JPEG.
    // ENG 004B1450; this = 0xAACF80
    inline Thiscall<uint32_t(void* self, const char* path, int w, int h, float scale)> renderSavePortrait{};
    // Plays an intro/cutscene video through DirectShow onto a fullscreen 1024x768 TL quad. thiscall on the movie
    // player (+4 skip count, +8 HWND): (IDirectDraw*, primary IDirectDrawSurface*, IAMMultiMediaStream*, 640, 480);
    // returns -1 when skipped.
    // ENG 006A0EA0
    inline Thiscall<int(void* self, IDirectDraw* ddraw, IDirectDrawSurface* primary, IUnknown* stream, int w, int h)>
        playVideo{};
    // cdecl (const char* path, IDirectDraw*, IAMMultiMediaStream** out) -> HRESULT: amstream with the DirectDraw
    // video stream, the default audio renderer and the file opened. The caller plays it if *out is set.
    inline Cdecl<HRESULT(const char* path, IUnknown* ddraw, IUnknown** stream)> openMovieStream{}; // ENG 006A0D80

    // The UI (sacred/ui.h).
    inline Global<cUI_Manager*> g_pUiManager{};         // ENG 017EEBBC
    // ENG 0075AA90; x, y in UI coordinates
    inline Thiscall<bool(cUI_Manager* self, int x, int y)> cUI_Manager_isCursorOverUi{};
    // Creates the in-game windows once; later calls return right away.
    inline Thiscall<void(cUI_Manager* self)> cUI_Manager_createGameWindows{}; // ENG 00759AF0
    // The help screen (H key, cUI_Manager::helpScreen): cUI_Manager_render calls it every frame with the screen for
    // the open windows (1 none, 2 inventory, 3 blacksmith, 4 combo master, 5 merchant, 6 world map, 7 rune exchange).
    // It puts the manager's help popups (cUI_Manager::helpPopups) at fixed 1024x768 positions, each next to or over
    // the window it explains, and sets their texts. Without the help screen it shows the [H] and [TAB] hints instead.
    // ENG 0075B4F0; screen: a short
    inline Thiscall<void(cUI_Manager* self, IDirect3DDevice7* device, uint32_t screen)> cUI_Manager_showHelp{};
    // ENG 006E6EA0; a, b, c: (?, const wstring*, bool)
    inline Thiscall<uint32_t(cUI_Popup* self, uint32_t a, uint32_t b, uint32_t c)> cUI_Popup_setText{};
    // ENG 006E6FB0; a, b, c: (?, text id, bool)
    inline Thiscall<uint32_t(cUI_Popup* self, uint32_t a, uint32_t b, uint32_t c)> cUI_Popup_setTextId{};
    inline Thiscall<void(cUI_Popup* self)> cUI_Popup_layout{};  // ENG 006E7AF0
    inline Thiscall<void(cUI_Window2* self)> cUI_Window2_layoutChildren{}; // ENG 00727B30
    // Draws the item held by the cursor at the cursor; every window that takes items (inventory, chest, cube,
    // trade, merchant, blacksmith) calls it from its render with (device, 1).
    // ENG 005DC430; flag: a short
    inline Thiscall<void(void* self, IDirect3DDevice7* device, int flag)> cInventoryEntry_render{};

    // UI-side reads of the cursor: cMouse_instance() followed by reads of +4/+8 only, and the calls of cMouse::getX
    // (ENG 00655850), getY (00655860) and getCursorPos. SacredBild gives them the cursor in the current UI frame.
    inline uintptr_t uiMouseReads[55]{};                // ENG 005DC316 006A3404 ... 00758A9D (tools/gen_sigs.py)
    inline uintptr_t uiGetXCalls[6]{};                  // ENG 005DC46B 006B6819 006B6FC7 006DADF5 006DBF81 006DD9E3
    inline uintptr_t uiGetYCalls[6]{};                  // ENG 005DC47B 006B6828 006B6FD6 006DAE04 006DBF90 006DD9F2
    inline uintptr_t uiCursorPosCalls[5]{};             // ENG 005DC495 006AD204 006C01A2 006EA500 006EA589
    // thiscall (int* x, int* y): the drawn cursor's top-left corner (+0xC/+0x10 minus the cursor's hot spot); writes
    // nothing while no cursor image is set (+0x64).
    inline Thiscall<void(cMouse* self, int* x, int* y)> cMouse_getCursorPos{}; // ENG 00655810

    // The texture manager (sacred/render.h).
    inline Global<cTextureManager*> g_pTextureManager{};  // ENG 013E7838
    inline Thiscall<cTexture*(cTextureManager* self, uint32_t handle, int flags)> cTextureManager_get{}; // ENG 0065ED90
    inline Thiscall<uint32_t(cTextureManager* self, uint32_t budgetBytes)> cTextureManager_init{}; // ENG 0065E7A0

    // cEngine
    // ENG 0060E350; loops until shutdown
    inline Thiscall<void(cEngine* self)> cEngine_renderThreadRun{};
    // Frame limiter: cdecl (double, uint16 fps); spins with Sleep(0) until 1/fps passed since its last return.
    // The render loop calls it with 60 before each flip (skipped if 0x182EE3C has 0x4000), the menu loop too.
    inline Cdecl<void(double unused, uint32_t fps)> frameLimiter{}; // ENG 0060A9F0
    inline uintptr_t renderLimiterReturn{};             // ENG 0060EA6E
    // cEngine_updateWorldCursor (0x611E70) asks the UI whether the cursor is over a window before picking.
    inline uintptr_t worldCursorUiTestCall{};           // ENG 00611EE3
    // Its draw of a hover cursor (talk, trade, use, attack, ...): pushed (cMouse ENG 00655060), cMouse_renderCursor,
    // popped (00655180); this is that renderCursor call's return address. The plain cursor is drawn by another call.
    inline uintptr_t worldCursorSpecialRenderReturn{};  // ENG 00612E6F
    inline uintptr_t captureLockBackReturn{};           // ENG 006136AB; after captureInternal's call to lockBack
    // Screenshots: dxDriver7_startCapture (ENG 00648660, thiscall (frames)) sets dxDriver7::captureFramesLeft; every
    // caller (Print Screen, the game's screenshot key, a debug key) asks for one frame. While it is set,
    // dxDriver7_flip locks the back buffer and calls captureScreenshot: mode -1 = one screenshot,
    // written by writeTga1024x768 (ENG 006482C0) as .\Capture\shotNNNN.tga, which a thread (ENG 00648430) converts to a
    // quality 50 JPEG through IJL. Both assume 1024x768 (the 32-bit path ignores the pitch). Modes >= 0 copy 3 MB
    // frames into a mapped file ("vidobj"), < -1 write them out as cap%04d.tga: only reached with more than one frame.
    inline Cdecl<void(void* bits, int pitch, int mode)> captureScreenshot{}; // ENG 006487D0

    // World <-> pixel conversion (cdecl (out, point, rotation, projection) -> out). Pixels assume a projection
    // spanning 1024x768 pixels: true for g_unzoomedProjection, not for the device projection (W x H).
    inline Cdecl<float*(float* out, const float* p, const float* m, const float* proj)> pixelsToWorld{}; // ENG 00623940
    inline Cdecl<float*(float* out, const float* p, const float* m, const float* proj)> worldToPixels{}; // ENG 00623B60
    inline Global<float[4][4]> g_unzoomedProjection{};  // ENG 0182ED70; row-major

    // The ground (sacred/world.h), the quad batcher and the render flags (sacred/render.h).
    // ENG 0062AE90
    inline Thiscall<void(cWorldView* self, IDirect3DDevice7* device, RowPos* row, int detail)>
        cWorldView_renderTileRow{};
    inline Thiscall<void(cWorldView* self, IDirect3DDevice7* device)> cWorldView_drawTileLayers{}; // ENG 0062D3C0
    inline Thiscall<void(cQuadBatcher* self, IDirect3DDevice7* device)> cQuadBatcher_flush{}; // ENG 00629340
    // ENG 00629180; quad: 4 vertices
    inline Thiscall<void(cQuadBatcher* self, IDirect3DDevice7* device, const float* quad)> cQuadBatcher_add{};
    // ENG 006292C0
    inline Thiscall<void(cQuadBatcher* self, IDirect3DDevice7* device, uint32_t handle)> cQuadBatcher_setTexture{};
    // The sprite batcher (sacred/render.h): flush when the texture handle changes, flush at the end of a pass.
    // ENG 00628F90
    inline Thiscall<void(cSpriteBatcher* self, IDirect3DDevice7* device, uint32_t handle)> cSpriteBatcher_setTexture{};
    inline Thiscall<void(cSpriteBatcher* self, IDirect3DDevice7* device)> cSpriteBatcher_flush{}; // ENG 00629050
    inline Cdecl<RenderFlags*()> renderFlags_instance{};  // ENG 00643110
    inline Thiscall<uint32_t(RenderFlags* self, uint32_t flag, uint32_t on)> renderFlags_set{}; // ENG 00643430
    inline Cdecl<WorldState*()> worldState_instance{};    // ENG 00417E70
    // Draws the collected water/lava tiles (glow pass, then the tiles) and sets the water ambience from their
    // count and average position.
    inline Thiscall<void(cWorldView* self, IDirect3DDevice7* device)> cWorldView_drawWaterTiles{}; // ENG 0062DD00
    // The object passes after the ground (sprites, buildings, creatures; 3D models through cObject3D::drawModel), in
    // this order with drawWaterTiles between them.
    inline Thiscall<void(cWorldView* self, IDirect3DDevice7* device)> cWorldView_drawObjects{}; // ENG 0062E410
    inline Thiscall<void(cWorldView* self, IDirect3DDevice7* device)> cWorldView_drawObjects2{}; // ENG 0062FF60
    // Per 3D model: visibility test, cGranny_render (model) and cGranny_renderShadow.
    // ENG 0044A9D0; flagsLow, flagsHigh: one 64-bit argument
    inline Thiscall<uint32_t(void* self, IDirect3DDevice7* device, void* model, void* instance, uint32_t flagsLow,
        uint32_t flagsHigh)> cObject3D_drawModel{};
    // Row walk (Sacred::RowPos): initRowWalk sets the view's even and odd rows from its top-left corner. The camera
    // position (view coordinates) is set by the same frame.
    // ENG 006328C0; pos: +4 x, +8 y
    inline Thiscall<void(cWorldView* self, const int32_t* pos, cMapData* map)> cWorldView_initRowWalk{};
    inline Global<int32_t> g_viewCameraX{};             // ENG 00AD7998
    inline Global<int32_t> g_viewCameraY{};             // ENG 00AD799C

    // Engine input: cEngine_receiveEvent (0x618090) passes mouse events to the UI manager first (UI coordinates)
    // and then to the world mouse handler, which picks with the event position.
    // ENG 006172C0; returns a bool
    inline Thiscall<uint32_t(cEngine* self, cEvent* event, int flag)> cEngine_worldMouse{};
    inline uintptr_t cEventMouseDown_vtable{};          // ENG 0089704C; x at +8, y at +0xC
    inline uintptr_t cEventMouseUp_vtable{};            // ENG 00899248
    // World-side cursor reads, redirected to physical coordinates: calls to cMouse::getX (ENG 00655850),
    // cMouse::getY (00655860) and cMouse_instance.
    inline uintptr_t worldGetXCalls[6]{};               // ENG 00611F54 00611F9D 0061273C 006127C8 00617DFC 00617E69
    inline uintptr_t worldGetYCalls[6]{};               // ENG 00611F47 00611F90 0061274D 006127D9 00617E0D 00617E5C
    inline uintptr_t worldMouseReads[5]{};              // ENG 004FB881 0060F268 006104C7 00611EC3 0062764E

    // Record caches of the map data (sacred/world.h, cMapData). recordMapFind is std::map::find on a RecordMap:
    // the node, or the head as end.
    inline Thiscall<LayerRecord*(cMapData* self, uint32_t id)> layerRecordCache{}; // ENG 00635FE0
    inline Thiscall<uint8_t*(cMapData* self, uint32_t id)> recordCache{}; // ENG 00635E50
    inline Thiscall<uint8_t*(RecordMap* map, const uint32_t* id)> recordMapFind{}; // ENG 00640410
    inline Global<uint32_t> g_recordStamp{};            // ENG 00CD7A50; the current time

    // The sound system's kernel mutex wrapper (sacred/sound.h).
    inline Thiscall<void(cMutex* self)> cMutex_lock{};      // ENG 0066FA00
    inline Thiscall<void(cMutex* self)> cMutex_unlock{};    // ENG 0066FA10

    // MSVC's __ftol: ST0 -> EDX:EAX, truncated (sets the x87 control word to chop around a fistp and back).
    inline uintptr_t rtFtol{};                          // ENG 0084A1F4

    // The game client (sacred/net.h).
    inline Global<cGCclass*> g_pGameClient{};           // ENG 0182EBF0
    // cGCclass_initNetwork sets TinCat's drv_disable_nagle (TCP_NODELAY on the game connection) to
    // "data flow == LAN" (cGCclass::dataFlow == 2): `cmp ebx, 2; sete al` after `xor eax, eax`.
    inline uintptr_t initNetworkNagleTest{};            // ENG 007D310E

    // cWorldView0 vtable slot 5: draws the isometric world (arg: device).
    inline Thiscall<void(cWorldView* self, IDirect3DDevice7* device)> cWorldView0_render{}; // ENG 00632140

    // cUI_Manager::render(device): letterbox bars + all UI windows.
    inline Thiscall<void(cUI_Manager* self, IDirect3DDevice7* device)> cUI_Manager_render{}; // ENG 00758ED0

    // Language. WinMain (0x817B30) sets g_language from settings.cfg's LANGUAGE (exact match with a code, else it
    // stays DE) or a code in lower case on the command line, formats ".\SCRIPTS\<code>\global.res" and passes it to
    // cTextTable_load, which ignores it in these builds: it loads the text from the exe's BINARY resource 107 (each
    // uint16 XORed with the one before it, the first with 0x45AD) into a buffer from the game's operator new.
    constexpr int languageCount = 11;
    inline Global<int32_t> g_language{};                // ENG 017E7D34; index into g_languageCodes
    // US DE FR SP IT PL HU JP VC RU CZ
    inline Global<const char[languageCount][16]> g_languageCodes{}; // ENG 00899394
    // ENG 0080E680; returns a bool, this = g_textTable
    inline Thiscall<int(cTextTable* table, const char* path)> cTextTable_load{};
    inline uintptr_t textTableAllocCall{};              // ENG 0080E6F0; its `call operator new` (cdecl (size))
    // Speech and sound effects: cMSS's constructor (only called by the instance getter 0x6770E0, on first use) opens
    // g_soundPakPath once and keeps the FILE*. initApp copies ".\PAK\SOUND.PAK" there (cMSS_setPakPath 0x677160)
    // and creates cMSS, but the startup movies (0x6A16E0, called from initApp before that) can create it first,
    // with the buffer's initial ".\PAK\SOUND.PAK".
    // ENG 00676200; (44100, 16, 1)
    inline Thiscall<void*(void* self, int rate, int bits, int channels)> cMSS_ctor{};
    inline Global<char[256]> g_soundPakPath{};          // ENG 009D760C

    // World pick: thiscall on the world view (x, y, excludeId, int32 outRect[3]) -> object id, 0 for none. Scans the
    // view's list of what can be picked on the screen (cWorldView::pickBegin), ranks the hits under (x, y) by
    // category (object vtable +0x24) and distance to their centers. Called by cEngine_updateWorldCursor (the hovered
    // object, kept in cMouse +0x6C) and by the world mouse handler (cEngine_worldMouse) for clicks.
    // ENG 00626C50
    inline Thiscall<uint32_t(cWorldView* self, int x, int y, uint32_t exclude, int32_t* rect)> worldPick{};
    // Objects: *g_pObjectManager is the object manager; getData is thiscall (id) -> object, 0 if there is none;
    // hero is thiscall () -> the local player's hero as cCreature*, 0 if there is none.
    inline Global<cObjectManager*> g_pObjectManager{};  // ENG 00AD5C40
    inline Thiscall<cObject*(cObjectManager* self, uint32_t id)> cObjectManager_getData{}; // ENG 005FE000
    inline Thiscall<cCreature*(cObjectManager* self)> cObjectManager_hero{}; // ENG 00603E30
    // MSVC's __RTDynamicCast: cdecl (object, 0, source type descriptor, target type descriptor, 0) -> object or 0.
    // ENG 0084A961
    inline Cdecl<void*(void* object, long vfDelta, void* source, void* target, int isReference)> rtDynamicCast{};
    inline uintptr_t cObject_typeDescriptor{};          // ENG 008EB648
    inline uintptr_t cCreature_typeDescriptor{};        // ENG 008EB660
    // thiscall on a creature (target creature) -> true if the target is alive and hostile to it (the cursor's
    // attack symbol).
    inline Thiscall<uint32_t(cCreature* self, cCreature* target)> cCreature_isEnemy{}; // ENG 00548F60

    // The options window's vtable (a cUI_Window2::Vtable), and the control functions its show and OK use.
    inline uintptr_t cUI_Options_vtable{};              // ENG 00897078
    inline Thiscall<void(cUI_Control2* self, uint32_t mask)> cUI_Control2_setFlags{}; // ENG 00732550
    inline Thiscall<void(cUI_Control2* self, uint32_t mask)> cUI_Control2_clearFlags{}; // ENG 007325C0
    inline Thiscall<void(cUI_Control2* self, UiRect* out)> cUI_Control2_getAbsoluteRect{}; // ENG 00732350
    inline Thiscall<uint32_t(cUI_Slider* self)> cUI_Slider_getValue{}; // ENG 00753430
    inline Thiscall<void(cUI_Slider* self, uint32_t value)> cUI_Slider_setValue{}; // ENG 007533B0

    // The engine singleton: cdecl (int, -1 to just get it) -> cEngine. getViewOffset is thiscall (int* x, int* y): how
    // far the view trails the hero; the hero stands at the screen center minus twice that (the hold-to-walk direction
    // at ENG 004FB8AF is measured from there).
    inline Cdecl<cEngine*(int create)> cEngine_instance{}; // ENG 0060D6C0
    inline Thiscall<void(cEngine* self, int* x, int* y)> cEngine_getViewOffset{}; // ENG 006113E0

    inline Thiscall<bool(cUI_Book* self, int x, int y, uint16_t* index)> cUI_Book_lineAt{}; // ENG 006B3640
    // What a click on a savegame row does.
    inline Thiscall<void(cUI_Savegame* self, uint16_t row)> cUI_Savegame_selectRow{}; // ENG 0071C360
    // Texts by id (sacred/text.h).
    inline Cdecl<cTextResources*()> textResources_instance{}; // ENG 006725E0
    inline Thiscall<const wchar_t* const*(cTextResources* self, uint32_t id)> textResources_get{}; // ENG 00672C90
    inline Global<cFontManager*> g_pFontManager{};      // ENG 00CDCA70
    // The Underworld add-on is there (the portal message box lists its 14th portal, the island).
    inline Global<uint8_t> g_hasAddon{};                // ENG 0182EBEC
    // The portal message box's text ids, made on its first render: the 14 surface portals, then the 14 underworld ones.
    inline Global<uint32_t> g_portalTexts{};            // ENG 017EA420
    // A byte per slot of the character screens: set, the slot can't be chosen.
    inline Global<uint8_t> g_characterSlotLocked{};     // ENG 017EA3D0
    // ENG 006F7130; (out rect, row, column)
    inline Thiscall<void(cUI_NetworkInfo* self, UiRect* out, uint32_t row, int column)> cUI_NetworkInfo_cellRect{};
    // The players of a network game (sacred/net.h).
    inline Global<cNetPlayers*> g_pNetPlayers{};        // ENG 0182EBE8
    inline Thiscall<uint32_t(cNetPlayers* self)> cNetPlayers_count{}; // ENG 007DB2C0

    // Move orders, as the world mouse handler (0x6172C0) and its hold-to-walk (0x60F130) give them: sendOrder is
    // thiscall on the cEngine (cCreature*, cOrder*), callee pops; it snaps a walk target to a walkable cell
    // and hands the order to the creature (vtable +0x18). Orders are built on the stack with cOrder_vtable.
    // g_worldInputFlags bit 2 (like cEngine flags 0x4000) makes the world mouse handler ignore the mouse.
    inline Thiscall<void(cEngine* self, cCreature* creature, cOrder* order)> cEngine_sendOrder{}; // ENG 00617030
    inline uintptr_t cOrder_vtable{};                   // ENG 0089095C
    inline Global<uint8_t> g_worldInputFlags{};         // ENG 00AB73DC
}
