#pragma once
#include <cstdint>

// Addresses in sacred.exe. They are found at startup from byte signatures (sacred_sigs.inc, generated by
// tools/gen_sigs.py from the German build and checked against the English one); the comments give the German
// addresses, the names match the Ghidra program "/sacred.exe (DE)". Lines that are only comments are not resolved.
namespace Sacred::Addr
{
    // dxDriver7 (DirectDraw7 + Direct3D7 wrapper, one global instance)
    // g_pDxDriver: DE 00CDA99C
    // dxDriver7_ctor: DE 00644960
    // dxDriver7_createSurface: DE 00644BE0
    // dxDriver7_createZBuffer: DE 00645000
    inline uintptr_t dxDriver7_init{};                  // DE 00645390
    inline uintptr_t dxDriver7_flip{};                  // DE 00645F70
    inline uintptr_t dxDriver7_lockBack{};              // DE 00646280
    // dxDriver7_unlockBack: DE 006462F0
    // dxDriver7_setFullViewport: DE 00646510
    // dxDriver7_drawTexturedQuad: DE 006466B0
    inline uintptr_t dxDriver7_drawLoadingScreen{};     // DE 006469D0
    // dxDriver7_beginScene: DE 00646F50
    // dxDriver7_endScene: DE 00646FD0

    // cDxDevices::findMode(w, h, bpp, flags) -> mode record; called once by initApp with 1024x768.
    inline uintptr_t cDxDevices_findMode{};             // DE 00644260

    // Return address of the CreateWindowExA call that creates the main game window.
    inline uintptr_t mainWindowCreateReturn{};          // DE 00813337

    // Mouse: getClientCursorPos(hwnd, POINT*) is the only cursor read; cMouse is the singleton the UI and world poll.
    inline uintptr_t getClientCursorPos{};              // DE 0066E500
    inline uintptr_t cMouse_instance{};                 // DE 006550F0
    inline uintptr_t cMouse_renderCursor{};             // DE 006555E0; (device, flag)

    // Renders the hero into the back buffer and reads the centered region back for the savegame JPEG.
    inline uintptr_t renderSavePortrait{};              // DE 004B1740; thiscall (path, w, h, scale), this = 0xAAAF00
    // Plays an intro/cutscene video through DirectShow onto a fullscreen 1024x768 TL quad. thiscall on the movie
    // player (+4 skip count, +8 HWND): (IDirectDraw*, primary IDirectDrawSurface*, IAMMultiMediaStream*, 640, 480);
    // returns -1 when skipped.
    inline uintptr_t playVideo{};                       // DE 006A0C60
    // cdecl (const char* path, IDirectDraw*, IAMMultiMediaStream** out) -> HRESULT: amstream with the DirectDraw
    // video stream, the default audio renderer and the file opened. The caller plays it if *out is set.
    inline uintptr_t openMovieStream{};                 // DE 006A0B40

    // UI framework (cUI_Control2 / cUI_Window2 / cUI_Manager)
    inline uintptr_t g_pUiManager{};                    // DE 017ECB3C; cUI_Manager*
    inline uintptr_t cUI_Manager_isCursorOverUi{};      // DE 0075A370; thiscall (x, y) -> bool, UI coordinates
    // cUI_Control2_ctor: DE 00731420; (name, x, y, w|h<<16, parent, flags)
    // cUI_Window2_addChild: DE 00727120; pushes into the children vector
    // Creates the in-game windows (UiManager::taskbar ...) once; later calls return right away.
    inline uintptr_t cUI_Manager_createGameWindows{};   // DE 007593D0; fastcall (manager)
    // The help screen (H key, UiManager::helpScreen): cUI_Manager_render calls it every frame with the screen for
    // the open windows (1 none, 2 inventory, 3 blacksmith, 4 combo master, 5 merchant, 6 world map, 7 rune exchange).
    // It puts the manager's help popups (UiManager::helpPopups) at fixed 1024x768 positions, each next to or over
    // the window it explains, and sets their texts. Without the help screen it shows the [H] and [TAB] hints instead.
    inline uintptr_t cUI_Manager_showHelp{};            // DE 0075ADD0; thiscall (device, short screen)
    // cUI_Window2_typeDescriptor: DE 009DE188
    // Popup (tooltip / hint) windows, owned by the manager (UiManager::popupsBegin). Callers set the popup's x/y
    // first, then its text with one of these, which also requests a new layout: the popup's render (vtable +0x14)
    // centers it on x/y and clamps it into 16..1008 x 16..752 before drawing.
    inline uintptr_t cUI_Popup_setText{};               // DE 006E6AE0; thiscall (?, const wstring*, bool)
    inline uintptr_t cUI_Popup_setTextId{};             // DE 006E6BF0; thiscall (?, text id, bool)
    // The layout: sizes the popup to its text; unless flags (+0x154) have 2 it centers the popup on x/y; with 8 it
    // clamps it into 16..1008 x 16..752 (a popup that would leave the 1024x768 screen sticks to its edge); with 0x20
    // it centers it on the screen (512, 384); then clears 0x40 and, unless 0x200, lays out the children.
    inline uintptr_t cUI_Popup_layout{};                // DE 006E7730; fastcall (popup)
    inline uintptr_t cUI_Window2_layoutChildren{};      // DE 007273C0; fastcall (window)
    // Draws the item held by the cursor at the cursor; every window that takes items (inventory, chest, cube,
    // trade, merchant, blacksmith) calls it from its render with (device, 1).
    inline uintptr_t cInventoryEntry_render{};          // DE 005DC3F0; thiscall (device, short)

    // UI-side reads of the cursor: cMouse_instance() followed by reads of +4/+8 only, and the calls of cMouse::getX
    // (DE 006559E0), getY (006559F0) and getCursorPos. SacredBild gives them the cursor in the current UI frame.
    inline uintptr_t uiMouseReads[55]{};                // DE 005DC2D6 006A31C4 ... 0075837D (tools/gen_sigs.py)
    inline uintptr_t uiGetXCalls[6]{};                  // DE 005DC42B 006B64B9 006B6C67 006DAB75 006DBD01 006DD793
    inline uintptr_t uiGetYCalls[6]{};                  // DE 005DC43B 006B64C8 006B6C76 006DAB84 006DBD10 006DD7A2
    inline uintptr_t uiCursorPosCalls[5]{};             // DE 005DC455 006ACEB4 006BFF32 006EA170 006EA1F9
    // thiscall (int* x, int* y): the drawn cursor's top-left corner (+0xC/+0x10 minus the cursor's hot spot); writes
    // nothing while no cursor image is set (+0x64).
    inline uintptr_t cMouse_getCursorPos{};             // DE 006559A0

    // Texture manager (one instance): loads textures on use, evicts least recently used ones above a budget.
    // initApp computes the budget from GlobalMemoryStatus and the reported video memory (min 32 MB).
    inline uintptr_t g_pTextureManager{};               // DE 013E57B8
    inline uintptr_t cTextureManager_init{};            // DE 0065EA20; thiscall (budgetBytes)

    // cEngine
    // initApp: DE 00815620
    inline uintptr_t cEngine_renderThreadRun{};         // DE 0060E3F0; fastcall (engine), loops until shutdown
    // Frame limiter: cdecl (double, uint16 fps); spins with Sleep(0) until 1/fps passed since its last return.
    // The render loop calls it with 60 before each flip (skipped if 0x182CDBC has 0x4000), the menu loop too.
    inline uintptr_t frameLimiter{};                    // DE 0060AA90
    inline uintptr_t renderLimiterReturn{};             // DE 0060EB0E
    // cEngine_updateWorldCursor (0x611F10) asks the UI whether the cursor is over a window before picking.
    inline uintptr_t worldCursorUiTestCall{};           // DE 00611F83
    // cEngine_captureInternal: DE 00613710
    inline uintptr_t captureLockBackReturn{};           // DE 0061374B; after captureInternal's call to lockBack
    // Screenshots: dxDriver7_startCapture (DE 00648790, thiscall (frames)) sets dxDriver7 +0xA8 (frames left) and
    // +0xAC (frames taken); every caller (Print Screen, the game's screenshot key, a debug key) asks for one frame.
    // While +0xA8 is set, dxDriver7_flip locks the back buffer and calls captureScreenshot: mode -1 = one screenshot,
    // written by writeTga1024x768 (DE 006483F0) as .\Capture\shotNNNN.tga, which a thread (DE 00648560) converts to a
    // quality 50 JPEG through IJL. Both assume 1024x768 (the 32-bit path ignores the pitch). Modes >= 0 copy 3 MB
    // frames into a mapped file ("vidobj"), < -1 write them out as cap%04d.tga: only reached with more than one frame.
    inline uintptr_t captureScreenshot{};               // DE 00648900; cdecl (bits, pitch, mode)

    // 3D model path: cCreature vtable[5] render -> cObject3D_render (needs the Granny model attached, flags bit 26)
    // -> cObject3D_drawModel -> cGranny_render* -> DrawIndexedPrimitiveStrided.
    inline uintptr_t cCreature_render{};                // DE 00599880; thiscall (device, 0)
    inline uintptr_t cObject3D_render{};                // DE 0044B400; thiscall (device, ?)
    inline uintptr_t cObject3D_drawModel{};             // DE 0044ABA0; thiscall (device, model, instance, flags64)

    // World <-> pixel conversion (cdecl (out, point, rotation, projection) -> out). Pixels assume a projection
    // spanning 1024x768 pixels: true for g_unzoomedProjection, not for the device projection (W x H).
    inline uintptr_t pixelsToWorld{};                   // DE 00623A20
    inline uintptr_t worldToPixels{};                   // DE 00623C40
    inline uintptr_t g_unzoomedProjection{};            // DE 0182CCF0

    // Ground: renderTileRow draws each tile's base through the quad batcher (cWorldView + 0x86890) and collects
    // tiles with blend layers into a fixed array (at most 0x6D5 per frame); after all rows cWorldView0_render
    // flushes the batcher and cWorldView_drawTileLayers draws the collected layers.
    inline uintptr_t cWorldView_renderTileRow{};        // DE 0062B000; thiscall (device, rowPos, detail)
    inline uintptr_t cWorldView_drawTileLayers{};       // DE 0062D530; thiscall (device)
    inline uintptr_t cQuadBatcher_flush{};              // DE 00629420; thiscall (device)
    // Draws the collected water/lava tiles (glow pass, then the tiles) and sets the water ambience from their
    // count and average position.
    inline uintptr_t cWorldView_drawWaterTiles{};       // DE 0062DE70; thiscall (device)
    // Row walk: initRowWalk sets the even and odd row positions (WorldView::rowEven/rowOdd) from the view's top-left
    // corner; cWorldView0_render then calls renderTileRow for each and steps it one tile row down (tile + 0x41,
    // y + 48), changing sector at sector edges. The camera position (view coordinates) is set by the same frame.
    inline uintptr_t cWorldView_initRowWalk{};          // DE 00632A30; thiscall (pos: +4 x, +8 y; map data)
    inline uintptr_t g_viewCameraX{};                   // DE 00AD5918; int32
    inline uintptr_t g_viewCameraY{};                   // DE 00AD591C; int32

    // Engine input: cEngine_receiveEvent (0x618130) passes mouse events to the UI manager first (UI coordinates)
    // and then to the world mouse handler, which picks with the event position.
    inline uintptr_t cEngine_worldMouse{};              // DE 00617360; thiscall (event, flag) -> bool
    inline uintptr_t cEventMouseDown_vtable{};          // DE 008950A8; x at +8, y at +0xC
    inline uintptr_t cEventMouseUp_vtable{};            // DE 00897248
    // World-side cursor reads, redirected to physical coordinates: calls to cMouse::getX (DE 006559E0),
    // cMouse::getY (006559F0) and cMouse_instance.
    inline uintptr_t worldGetXCalls[6]{};               // DE 00611FF4 0061203D 006127DC 00612868 00617E9C 00617F09
    inline uintptr_t worldGetYCalls[6]{};               // DE 00611FE7 00612030 006127ED 00612879 00617EAD 00617EFC
    inline uintptr_t worldMouseReads[5]{};              // DE 004FB6C1 0060F308 00610567 00611F63 0062772E

    // Record caches of the map data object (constructor 0x6336F0, clear 0x633F80): thiscall (id) -> record, 0 if
    // id is 0. Each looks the id up in its own std::map<uint32_t, record> (find 0x6404C0: thiscall (&key) on the
    // map, returns the node or the head as end; node +0x10 key, +0x14 record), stamps the node with the current
    // time (0xCD59D0) on a hit, and on a miss reads the record from a data file, inserts it and may evict the node
    // with the oldest stamp. 0x6360E0 holds the ground layer records (16 bytes, map at +0xDE5C, stamp node +0x24),
    // 0x635F50 the 64-byte records also used by game logic (map at +0xDE50, stamp node +0x54).
    inline uintptr_t layerRecordCache{};                // DE 006360E0
    inline uintptr_t recordCache{};                     // DE 00635F50
    inline uintptr_t recordMapFind{};                   // DE 006404C0
    inline uintptr_t g_recordStamp{};                   // DE 00CD59D0

    // Game client (cGCclass, one instance). cGCclass_initNetwork (0x7D2410) binds a UDP socket (SO_REUSEADDR) to
    // NETWORK_PORT_LISTEN for the LAN list; cGCclass_pollLanGames (0x7D2E20) reads the gameservers' announcements
    // from it with select/__WSAFDIsSet/recvfrom (their only use in the exe) and drops games that were silent for
    // 5 s. cGCclass_joinLanGame (0x7D3530) connects to the address inside the announcement.
    inline uintptr_t g_pGameClient{};                   // DE 0182CB70
    constexpr uintptr_t gameClient_lanSocket = 0x14;
    // cGCclass_initNetwork sets TinCat's drv_disable_nagle (TCP_NODELAY on the game connection) to
    // "data flow == LAN" (cGCclass + 0x40414 == 2): `cmp ebx, 2; sete al` after `xor eax, eax`.
    inline uintptr_t initNetworkNagleTest{};            // DE 007D294E

    // cWorldView0 vtable slot 5: draws the isometric world (arg: device).
    inline uintptr_t cWorldView0_render{};              // DE 006322B0

    // cUI_Manager::render(device): letterbox bars + all UI windows.
    inline uintptr_t cUI_Manager_render{};              // DE 007587B0

    // Language. WinMain (0x816BD0) sets g_language from settings.cfg's LANGUAGE (exact match with a code, else it
    // stays DE) or a code in lower case on the command line, formats ".\SCRIPTS\<code>\global.res" and passes it to
    // cTextTable_load, which ignores it in these builds: it loads the text from the exe's BINARY resource 107 (each
    // uint16 XORed with the one before it, the first with 0x45AD) into a buffer from the game's operator new.
    inline uintptr_t g_language{};                      // DE 017E5CB4; int32, index into g_languageCodes
    inline uintptr_t g_languageCodes{};                 // DE 00897394; char[16] each: US DE FR SP IT PL HU JP VC RU CZ
    constexpr int languageCount = 11;
    inline uintptr_t cTextTable_load{};                 // DE 0080DBF0; thiscall (path) -> bool, this = g_textTable
    inline uintptr_t textTableAllocCall{};              // DE 0080DC60; its `call operator new` (cdecl (size))
    // Speech and sound effects: cMSS's constructor (only called by the instance getter 0x6773C0, on first use) opens
    // g_soundPakPath once and keeps the FILE*. initApp copies ".\PAK\SOUND.PAK" there (cMSS_setPakPath 0x677440)
    // and creates cMSS, but the startup movies (0x6A14A0, called from initApp before that) can create it first,
    // with the buffer's initial ".\PAK\SOUND.PAK".
    inline uintptr_t cMSS_ctor{};                       // DE 006764E0; thiscall (44100, 16, 1)
    inline uintptr_t g_soundPakPath{};                  // DE 009D5624; char[256]
}

// Text table (g_textTable, DE 0182CCD0; a static object, destroyed at exit). global.res, in memory as on disk:
// uint32 count, count entries {uint32 id, uint32 offset, uint32 flags, uint32 bytes} by ascending id, then the
// UTF-16 strings; an entry's string starts at 4 + offset.
namespace Sacred::TextTable
{
    constexpr uintptr_t data = 0x00;         // uint8_t*
    constexpr uintptr_t size = 0x04;         // uint32 bytes
}

// dxDriver7 member offsets (identical in the ENG and DE builds).
namespace Sacred::DxDriver
{
    constexpr uintptr_t height = 0x1C;       // uint16
    constexpr uintptr_t width = 0x20;        // uint16
    constexpr uintptr_t windowed = 0x90;     // 1 = fullscreen, else windowed
    constexpr uintptr_t bpp = 0x94;
    constexpr uintptr_t hwnd = 0xB0;
    constexpr uintptr_t ddraw = 0xB4;        // IDirectDraw7*
    constexpr uintptr_t primary = 0xB8;      // IDirectDrawSurface7*
    constexpr uintptr_t back = 0xBC;         // IDirectDrawSurface7* (3D render target)
    constexpr uintptr_t d3d = 0xC8;          // IDirect3D7*
    constexpr uintptr_t device = 0xCC;       // IDirect3DDevice7*
}

// cUI_Control2 member offsets. Window children keep absolute screen coordinates.
namespace Sacred::UiControl
{
    constexpr uintptr_t flags = 0x10;        // bit 0: visible
    constexpr uintptr_t x = 0x24;
    constexpr uintptr_t y = 0x28;
    constexpr uintptr_t width = 0x2C;        // int16
    constexpr uintptr_t height = 0x2E;       // int16
    constexpr uintptr_t name = 0x30;         // char[0x20]
    constexpr uintptr_t parent = 0x50;
    constexpr uintptr_t childrenBegin = 0x78; // cUI_Window2 only: std::vector<cUI_Control2*>
    constexpr uintptr_t childrenEnd = 0x7C;
}

// cEngine member offsets.
namespace Sacred::Engine
{
    constexpr uintptr_t flags = 0x54;        // 0x10000 loading screen, 0x20000 fade out, 0x40000 fade in, 0x80000 black
}

// cWorldView member offsets (ground layers).
namespace Sacred::WorldView
{
    constexpr uintptr_t quadBatcher = 0x86890;
    constexpr uintptr_t layeredTileCount = 0x3FF1C;
    constexpr uint32_t layeredTileCapacity = 0x6D5;
    // Animated (water/lava, record type 0x90/0xA0) tiles: renderTileRow appends 0x98-byte entries at +0x3FF2C without
    // a bounds check; cWorldView_drawWaterTiles draws them after all rows. Entry 1750 would overwrite the count.
    constexpr uintptr_t waterTileCount = 0x80E3C;
    constexpr uint32_t waterTileCapacity = (0x80E3C - 0x3FF2C) / 0x98;
    // Row walk positions: x, y (float), tile (int16, row * 64 + column in its sector), sector (int16, 3x3 grid of
    // loaded sectors around the camera, row * 3 + column), steps (int16).
    constexpr uintptr_t rowEven = 0x970D4;
    constexpr uintptr_t rowOdd = 0x970E4;   // even + (48, 24): one tile column further
    constexpr uintptr_t rowEdgeLeft = 0x96AB8;  // 6: renderTileRow draws ground from column edgeLeft - 1 ...
    constexpr uintptr_t rowEdgeRight = 0x96ABC; // 6: ... to column rowLength - edgeRight + 1 (rest: margins)
    constexpr uintptr_t rowLength = 0x96AC8;    // tiles per row: view width / 96 + 12
}

// cTextureManager member offsets.
namespace Sacred::TextureManager
{
    constexpr uintptr_t usedBytes = 0xC001C;
    constexpr uintptr_t budgetBytes = 0xC0020;
}

// cMouse member offsets.
namespace Sacred::Mouse
{
    constexpr uintptr_t x = 0x04;
    constexpr uintptr_t y = 0x08;
    constexpr uintptr_t cursorImage = 0x64;  // getCursorPos writes its outputs only while this is set
}

// cUI_Manager: top-level game windows created by createGameWindows live in this pointer range.
namespace Sacred::UiManager
{
    constexpr uintptr_t flags = 0x08;        // 0x01 menus, 0x04 in game, 0x10 cinematic
    constexpr uint32_t inGame = 0x04;
    constexpr uint32_t helpScreen = 0x200;   // the help screen (H key) is shown
    // uint16[16]: indices into the popups (popupsBegin) used by the help screen, in the order of its entries.
    constexpr uintptr_t helpPopups = 0x56;
    constexpr uintptr_t firstGameWindow = 0x80;
    constexpr uintptr_t lastGameWindow = 0xD8;
    // In-game windows (cUI_Window2 subclasses) and their rects in the 1024x768 layout.
    constexpr uintptr_t taskbar = 0x80;      // 0,676 1024x92
    constexpr uintptr_t inventory = 0x84;    // 0,388 640x256
    constexpr uintptr_t equipment = 0x88;    // 656,388 256x256
    constexpr uintptr_t blacksmith = 0x8C;   // 0,0 640x352
    constexpr uintptr_t merchant = 0x90;     // 0,0 640x336
    constexpr uintptr_t megamap = 0x94;      // full screen
    constexpr uintptr_t overviewMap = 0x98;  // 162,120 700x525
    constexpr uintptr_t minimap = 0x9C;      // UI_WND_MERC: minimap and party portraits, 932,0 92x676
    constexpr uintptr_t stats = 0xA0;        // 656,0 256x420
    constexpr uintptr_t console = 0xA4;      // chat input, 256,640 512x128
    constexpr uintptr_t questbook = 0xA8;    // 64,64 832x576
    constexpr uintptr_t savegame = 0xAC;     // full screen
    constexpr uintptr_t escMenu = 0xB0;      // 380,284
    constexpr uintptr_t purchase = 0xB4;     // 160,96
    constexpr uintptr_t master = 0xB8;       // combat art master, 0,0 640x336
    constexpr uintptr_t options = 0xBC;      // full screen
    constexpr uintptr_t chest = 0xC0;        // 0,0 640x320
    constexpr uintptr_t horse = 0xC4;        // 256,204 512x360
    constexpr uintptr_t netInfo = 0xC8;      // 352,406 320x240
    constexpr uintptr_t netPortraits = 0xCC; // 0,0 896x64
    constexpr uintptr_t character = 0xD0;    // full screen
    constexpr uintptr_t cube = 0xD4;         // 0,0 640x320
    constexpr uintptr_t trade = 0xD8;        // 0,0 640x320
    // std::vector of popup windows (vtable: render +0x14, events +0x10, hit test +0x1c, like a window).
    constexpr uintptr_t popupsBegin = 0x124;
    constexpr uintptr_t popupsEnd = 0x128;
}

// cUI_Window2 virtual functions (thiscall; byte offsets into the vtable) that SacredBild wraps for UI frames.
namespace Sacred::UiWindowSlot
{
    constexpr uintptr_t receiveEvent = 0x10; // (cEvent*) -> bool; mouse buttons carry x/y at +8/+0xC
    constexpr uintptr_t render = 0x14;       // (device)
    constexpr uintptr_t isInside = 0x1C;     // (x, y) -> bool
    constexpr uintptr_t show = 0x24;         // (bool)
    constexpr uintptr_t render2 = 0x44;      // (device, ?, ?): blacksmith, merchant, net portraits draw here
}

// cUI_Taskbar2 members.
namespace Sacred::Taskbar
{
    // Embedded button ("+", opens the character stats; blinks with flag 0x400000 while points are unspent). Placed at
    // the absolute position (898, 10) of the stats window's close button, which covers it while the window is open.
    constexpr uintptr_t levelUpButton = 0x18C;
    constexpr int levelUpX = 898;
    constexpr int levelUpY = 10;
}

// Popup (tooltip) window: a cUI_Window2 with its own flags.
namespace Sacred::Popup
{
    constexpr uintptr_t flags = 0x154;
    constexpr uint32_t clampToScreen = 0x08;    // layout keeps it 16 px inside the 1024x768 screen
    constexpr uint32_t centerOnScreen = 0x20;   // layout centers it on (512, 384)
    constexpr uint32_t keepChildren = 0x200;    // layout leaves the children where they are
}

// cEvent member offsets (mouse button events: cEventMouseDown_vtable / cEventMouseUp_vtable).
namespace Sacred::MouseEvent
{
    constexpr uintptr_t x = 0x08;
    constexpr uintptr_t y = 0x0C;
}
