# Compiles the backend's vertex shaders to vs_2_0 bytecode with fxc from the Windows SDK, so the DLL needs no shader
# compiler at run time:
#   src/ddraw9/skin.hlsl (both variants) -> src/ddraw9/skin_shaders.inc
#   src/ddraw9/ground.hlsl               -> src/ddraw9/ground_shaders.inc
# Usage: python tools/gen_shaders.py   (FXC = path to fxc.exe if it is not found in the Windows Kits folder)
import glob, os, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADERS = [
    ('skin.hlsl', 'skin_shaders.inc', [('kSkinShader', []), ('kSkinShaderDiffuse', ['/D', 'DIFFUSE=1'])]),
    ('ground.hlsl', 'ground_shaders.inc', [('kGroundShader', [])]),
]


def find_fxc():
    if os.environ.get('FXC'):
        return os.environ['FXC']
    found = sorted(glob.glob(r'C:\Program Files (x86)\Windows Kits\10\bin\10.*\x64\fxc.exe'))
    if not found:
        sys.exit('fxc.exe not found; set FXC')
    return found[-1]


def compile_variant(fxc, source, name, defines):
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, 'shader.h')
        cmd = [fxc, '/nologo', '/T', 'vs_2_0', '/E', 'main', '/O3', '/Vn', name, '/Fh', out, *defines, source]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            sys.exit(f'fxc failed for {name}:\n{result.stdout}{result.stderr}')
        with open(out) as f:
            text = f.read()
    # Keep the instruction listing fxc writes as a comment (for review), the byte array as is.
    return text.replace('const BYTE', 'static const BYTE')


def main():
    fxc = find_fxc()
    for source, output, variants in SHADERS:
        src = os.path.join(ROOT, 'src', 'ddraw9', source)
        out = os.path.join(ROOT, 'src', 'ddraw9', output)
        parts = [f'// Generated by tools/gen_shaders.py from src/ddraw9/{source} -- do not edit by hand.\n']
        for name, defines in variants:
            parts.append(compile_variant(fxc, src, name, defines))
        with open(out, 'w', newline='\n') as f:
            f.write('\n'.join(parts))
        print(f'wrote {os.path.relpath(out, ROOT)}')


if __name__ == '__main__':
    main()
